"""Add role column to User

Revision ID: 1365de5f8e99
Revises: a255631d107c
Create Date: 2025-10-14 00:08:41.444002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1365de5f8e99'
down_revision = 'a255631d107c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
